
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      POSTGRES_CONN: postgres://user:password@db:5432/mydb?sslmode=disable
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend-react/Dockerfile
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  pgdata:
